{{- $modelName := .Values.model.name -}}
{{- $ns := .Values.namespace -}}
{{- $rel := .Release.Name -}}

{{- range $v := list "stable" "canary" }}
{{- $tag := ternary $.Values.model.image.stableTag $.Values.model.image.canaryTag (eq $v "stable") }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $modelName }}-{{ $v }}
  namespace: {{ $ns }}
  labels:
    app: {{ $modelName }}
    release: {{ $rel }}
    version: {{ $v }}
spec:
  replicas: {{ $.Values.model.replicaCount }}
  selector:
    matchLabels:
      app: {{ $modelName }}
      release: {{ $rel }}
      version: {{ $v }}
  template:
    metadata:
      labels:
        app: {{ $modelName }}
        release: {{ $rel }}
        version: {{ $v }}
    spec:
      containers:
      - name: {{ $modelName }}
        image: "{{ $.Values.model.image.repository }}:{{ $tag }}"
        imagePullPolicy: {{ $.Values.model.image.pullPolicy }}
        # # Add directory
        # workingDir: /root

        ports:
          - name: http
            containerPort: {{ $.Values.model.service.targetPort }}
            protocol: TCP
        env:
          - name: MODEL_PORT
            value: {{ $.Values.model.env.modelPort | quote }}
        {{- if $.Values.resources }}
        resources:
          {{- toYaml $.Values.resources | nindent 10 }}
        {{- end }}
---
{{- end }}
