apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.model.name }}-stable
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.model.name }}
    release: {{ .Release.Name }}
    version: {{ .Values.app.version }}
spec:
  replicas: {{ .Values.model.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.model.name }}
      release: {{ .Release.Name }}
      version: {{ .Values.app.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.model.name }}
        release: {{ .Release.Name }}
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: {{ .Values.model.name }}
        image: "{{ .Values.model.image.repository }}:{{ .Values.model.image.stableTag }}"
        imagePullPolicy: {{ .Values.model.image.pullPolicy }}
        # # Add directory
        # workingDir: /root

        ports:
          - name: http
            containerPort: {{ .Values.model.service.targetPort }}
            protocol: TCP
        env:
          - name: MODEL_PORT
            value: {{ .Values.model.env.modelPort | quote }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
