apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-stable
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
    version: {{ .Values.app.version }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}
      version: {{ .Values.app.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
        version: {{ .Values.app.version }}
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.stableTag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        volumeMounts:
          - name: shared-volume
            mountPath: /app/shared
        ports:
          - name: http
            containerPort: {{ .Values.app.service.targetPort }}
            protocol: TCP
        env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-config
                key: SERVER_PORT

          - name: MODEL_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-config
                key: MODEL_SERVICE_URL

          - name: MODEL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-config
                key: MODEL_HOST

          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: {{ required "app.secret.secretName is required (Excellence Requirement - Pre-deployed Secret)" .Values.app.secret.secretName }}
                # name: {{ .Values.app.secret.secretName }}
                key: {{ .Values.app.secret.key }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
