apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    version: canary
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}
      version: canary
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
        version: canary
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.canaryTag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.app.service.targetPort }}
            protocol: TCP
        env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-config
                key: SERVER_PORT

          - name: MODEL_SERVICE_URL
            value: "http://{{ .Values.model.name }}-canary:{{ .Values.model.service.port }}"

          # - name: MODEL_HOST
          #   value: "http://{{ .Values.model.name }}-canary:{{ .Values.model.service.port }}"
            
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.name }}-secret
                key: MY_SECRET

          - name: EXPERIMENT_VARIANT
            value: "canary"
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
