apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata: { name: my-gateway }
spec:
  selector: { istio: ingressgateway }
  servers:
  - port: { number: 80, name: http, protocol: HTTP }
    hosts: [ "*" ]
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: sms-app-dr }
spec:
  host: sms-app
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: { name: my-entry-service }
spec:
  gateways: [ my-gateway ]
  hosts: [ "*" ]
  http:
  - match:
    - uri: { prefix: / }
    route:
    - destination: { host: sms-app, subset: latest }
      weight: 90
    - destination: { host: sms-app, subset: v1 }
      weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: sms-model-dr }
spec:
  host: sms-model
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }