# 1. Basic Istio setup for traffic management
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata: { name: my-gateway }
spec:
  selector: { istio: ingressgateway }
  servers:
  - port: { number: 80, name: http, protocol: HTTP }
    hosts: [ "*" ]
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: sms-app-dr }
spec:
  host: sms-app
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: { name: my-entry-service }
spec:
  gateways: [ my-gateway ]
  hosts: [ "*" ]
  http:
  - match:
    - uri: { prefix: / }
    route:
    - destination: { host: sms-app, subset: latest }
      weight: 90
    - destination: { host: sms-app, subset: v1 }
      weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: { name: sms-model-dr }
spec:
  host: sms-model
  subsets:
  - name: latest
    labels: { version: latest }
  - name: v1
    labels: { version: v1 }
---
# 2. Additional Use Case: Request rate limit
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-limit-filter
  namespace: istio-system # better enforcement + debugging
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      # do this before every request to the gateway
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ratelimit
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
          domain: ratelimit
          failure_mode_deny: true
          timeout: 10s
          rate_limit_service:
            grpc_service:
              envoy_grpc:
                cluster_name: outbound|8081||ratelimit.istio-system.svc.cluster.local
                authority: ratelimit.istio-system.svc.cluster.local
            transport_api_version: V3
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: ""
          route:
            action: ANY
    patch:
      operation: MERGE
      # Rate Limit Rules
      value:
        rate_limits:
          - actions:
            - request_headers:
                header_name: "X-Access-User"
                descriptor_key: "user"
          - actions:
            - generic_key:
                descriptor_value: "all"
          # value:
          #   stat_prefix: http_local_rate_limiter
          #   # each minute user gets 10 requests, reset every minute
          #   token_bucket:
          #     max_tokens: 10
          #     tokens_per_fill: 10
          #     fill_interval: 60s
          #   # rate limit 100% of requests for now
          #   filter_enabled:
          #     default_value:
          #       numerator: 100
          #       denominator: HUNDRED
          #   filter_enforced:
          #     default_value:
          #       numerator: 100
          #       denominator: HUNDRED