apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  namespace: monitoring
  labels: { release: prometheus }
spec:
  selector:
    matchLabels: { app: sms-app }
  namespaceSelector:
    matchNames:
      - default
  endpoints: [ { port: http, path: /sms/metrics, interval: 1s } ]
  # Add label for Prometheus Grafana integration
  targetLabels:
    - version