apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: istio-system
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: user
        rate_limit:
          unit: minute
          requests_per_unit: 10
      
      - key: generic_key
        value: all
        rate_limit:
          unit: minute
          requests_per_unit: 10