apiVersion: v1
kind: Service
metadata:
  name: sms-app
  labels:
    app: sms-app
spec:
  selector:
    app: sms-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP