apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-app
  labels:
    app: sms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-app
  template:
    metadata:
      labels:
        app: sms-app
    spec:
      containers:
      - name: sms-app
        image: ghcr.io/doda25-team16/app:latest
        ports:
          - containerPort: 8080
        env:
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: sms-app-config
                key: SERVER_PORT

          - name: MODEL_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: sms-app-config
                key: MODEL_SERVICE_URL
          
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: sms-app-secret
                key: MY_SECRET
          