apiVersion: v1
kind: Service
metadata:
  name: sms-model
  labels:
    app: sms-model
spec:
  selector:
    app: sms-model
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP