---
- hosts: all
  become: yes
  vars:
    kube_user: "vagrant"
    ansible_user_home: "/home/vagrant"
  tasks:
    - name: Install worker dependencies
      debug: 
        msg: "This is where kubernetes worker setup happens"

    - name: Check if worker node already joined the cluster
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    # Step 18
    - name: Generate kubeadm join command
      delegate_to: ctrl
      become: yes
      command: kubeadm token create --print-join-command
      register: join_cmd
      changed_when: false
      when: not kubelet_conf.stat.exists

    # Step 19
    - name: Join cluster
      become: yes
      shell: "{{ join_cmd.stdout }} --ignore-preflight-errors=all"
      register: join_cluster_result
      retries: 3
      delay: 30
      until: join_cluster_result.rc == 0
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: not kubelet_conf.stat.exists